[tool.pytest.ini_options]
filterwarnings = [
#    "error",
    "ignore::UserWarning",
    # note the use of single quote below to denote "raw" strings in TOML
    'ignore:jsonschema.RefResolver is deprecated:DeprecationWarning',
    'ignore:jsonschema.exceptions.RefResolutionError is deprecated:DeprecationWarning',
]
testpaths = [
    "tests",
    "integration",
]
pythonpath = [
    "src",
]